import type {
  AppSettings,
  CourseCard,
  CourseDetail,
  DashboardSnapshot,
  LessonPlayerPayload,
  LicenseState,
  OperationalProfile,
  SearchResult,
} from "@/types/domain";

const sampleLessons = [
  {
    id: 110,
    courseId: 1,
    sectionId: 11,
    title: "02. Async Await sin fricción",
    relativePath: "Modulo 2/02-async-await.mp4",
    absolutePath: "D:/Cursos/React/Modulo 2/02-async-await.mp4",
    durationSeconds: 1740,
    progressSeconds: 628,
    progressPercent: 36,
    speed: 1.25,
    volume: 0.9,
    lastViewedAt: new Date().toISOString(),
    completed: false,
    subtitlePath: "D:/Cursos/React/Modulo 2/02-async-await.es.vtt",
    thumbnailPath: null,
    mediaInfo: {
      durationSeconds: 1740,
      width: 1920,
      height: 1080,
      videoCodec: "h264",
      audioCodec: "aac",
      container: "mp4",
      subtitleTracks: ["webvtt"],
    },
  },
  {
    id: 111,
    courseId: 1,
    sectionId: 11,
    title: "03. Hooks que sí escalan",
    relativePath: "Modulo 2/03-hooks.mp4",
    absolutePath: "D:/Cursos/React/Modulo 2/03-hooks.mp4",
    durationSeconds: 2280,
    progressSeconds: 0,
    progressPercent: 0,
    speed: 1,
    volume: 1,
    lastViewedAt: null,
    completed: false,
    subtitlePath: null,
    thumbnailPath: null,
    mediaInfo: {
      durationSeconds: 2280,
      width: 1920,
      height: 1080,
      videoCodec: "h264",
      audioCodec: "aac",
      container: "mp4",
      subtitleTracks: [],
    },
  },
];

export const mockSettings: AppSettings = {
  locale: "es-MX",
  completionThresholdPercent: 92,
  internetEnrichmentEnabled: false,
  offlineModeEnabled: true,
  thumbnailQuality: "balanced",
  modelName: "Xenova/all-MiniLM-L6-v2",
  coverEnrichmentProvider: "openverse",
  cardDensity: "comfortable",
  reducedMotion: false,
  aiProcessingEnabled: false,
  lowResourceMode: false,
};

export const mockLicenseState: LicenseState = {
  edition: "Professional Trial",
  status: "trial",
  activationMode: "trial",
  licenseId: null,
  licensedTo: null,
  email: null,
  company: null,
  issuedAt: new Date().toISOString(),
  expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
  activatedAt: new Date().toISOString(),
  trialStartedAt: new Date().toISOString(),
  trialEndsAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
  trialDaysRemaining: 12,
  graceMessage: "Prueba local activa en este equipo.",
  features: [
    "Reindexación IA local completa",
    "Enriquecimiento remoto opt-in",
    "Exportación e importación de respaldos",
    "Soporte prioritario por correo",
  ],
  publicKeyConfigured: true,
  canStartTrial: false,
  tokenLast4: null,
};

export const mockOperationalProfile: OperationalProfile = {
  productName: "OrganiCursos",
  version: "0.1.0",
  identifier: "mx.web.zolvek.organicursos",
  platform: "windows",
  arch: "x64",
  appDataDir: "C:/OrganiCursos/data",
  cacheDir: "C:/OrganiCursos/cache",
  databasePath: "C:/OrganiCursos/data/atlas-courses.db",
  vectorEnabled: true,
  licensePublicKeyConfigured: true,
  portableMode: false,
};

export const mockCourses: CourseCard[] = [
  {
    id: 1,
    title: "React Profundo para Apps Reales",
    subtitle: "Arquitectura, estado y patrones para equipos serios",
    coverPath: null,
    category: "Programación",
    difficulty: "Intermedio",
    inferredTitle: "React profundo para apps reales",
    inferredCategory: "Programación",
    inferredDifficulty: "Intermedio",
    suggestedDescription:
      "Curso centrado en React, asincronía, hooks y patrones de arquitectura para aplicaciones mantenibles.",
    inferenceConfidence: 0.91,
    lessonCount: 42,
    totalDurationSeconds: 54320,
    progressPercent: 38,
    lastViewedAt: new Date().toISOString(),
    isFavorite: true,
  },
  {
    id: 2,
    title: "Finanzas Personales con Criterio",
    subtitle: "Bases, presupuesto y visión patrimonial",
    coverPath: null,
    category: "Finanzas",
    difficulty: "Principiante",
    inferredTitle: "Finanzas personales con criterio",
    inferredCategory: "Finanzas",
    inferredDifficulty: "Principiante",
    suggestedDescription:
      "Recorrido introductorio sobre presupuesto, ahorro, control de gastos y fundamentos patrimoniales.",
    inferenceConfidence: 0.87,
    lessonCount: 17,
    totalDurationSeconds: 17200,
    progressPercent: 0,
    lastViewedAt: null,
    isFavorite: false,
  },
];

export const mockDashboard: DashboardSnapshot = {
  continueWatching: sampleLessons,
  recentCourses: mockCourses,
  recentlyViewed: sampleLessons,
  recentlyAdded: [sampleLessons[1], sampleLessons[0]],
  favoriteCourses: [mockCourses[0]],
  stats: {
    courses: 12,
    lessons: 248,
    hoursWatched: 36,
    activeLibraries: 3,
  },
};

export const mockCourseDetail: CourseDetail = {
  ...mockCourses[0],
  description:
    "Curso organizado localmente a partir de vídeos, PDFs y subtítulos; la app consolidó el temario y sugirió etiquetas con embeddings locales.",
  tags: ["react", "hooks", "frontend", "arquitectura"],
  aiTags: [
    { name: "react", confidence: 0.96, source: "ai" },
    { name: "asincronía", confidence: 0.83, source: "ai" },
    { name: "hooks", confidence: 0.81, source: "ai" },
  ],
  similarCourses: [
    {
      courseId: 1,
      relatedCourseId: 2,
      similarity: 0.79,
      relationKind: "related",
      status: "suggested",
      evidence: "Coinciden patrones de aprendizaje estructurado y enfoque introductorio.",
      relatedCourse: mockCourses[1],
    },
  ],
  sections: [
    {
      id: 11,
      courseId: 1,
      title: "Módulo 2 · Estado y asincronía",
      position: 2,
      lessons: sampleLessons,
    },
  ],
  assets: [
    {
      id: 710,
      lessonId: 110,
      courseId: 1,
      assetKind: "pdf",
      title: "GuÃ­a de Hooks Avanzados",
      absolutePath: "D:/Cursos/React/Modulo 2/guia-hooks.pdf",
      relativePath: "Modulo 2/guia-hooks.pdf",
      extension: "pdf",
      fileSizeBytes: 440321,
      extractedTextPreview: "Resumen de composiciÃ³n de hooks, side effects y patrones de extracciÃ³n.",
      thumbnailPath: null,
    },
    {
      id: 711,
      lessonId: 110,
      courseId: 1,
      assetKind: "subtitle",
      title: "SubtÃ­tulos ES",
      absolutePath: "D:/Cursos/React/Modulo 2/02-async-await.es.vtt",
      relativePath: "Modulo 2/02-async-await.es.vtt",
      extension: "vtt",
      fileSizeBytes: 8243,
      extractedTextPreview: "Async await no bloquea el hilo principal.",
      thumbnailPath: null,
    },
  ],
  notes: [
    {
      id: 900,
      courseId: 1,
      lessonId: 110,
      timestampSeconds: 603,
      body: "Comparar este patrón con Suspense y transición concurrente.",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

export const mockLessonPayload: LessonPlayerPayload = {
  lesson: sampleLessons[0],
  notes: mockCourseDetail.notes,
  bookmarks: [
    {
      id: 501,
      lessonId: 110,
      timestampSeconds: 603,
      label: "Ejemplo de fetch con cancelación",
      createdAt: new Date().toISOString(),
    },
  ],
  assets: [
    {
      id: 710,
      lessonId: 110,
      courseId: 1,
      assetKind: "pdf",
      title: "Guía de Hooks Avanzados",
      absolutePath: "D:/Cursos/React/Modulo 2/guia-hooks.pdf",
      relativePath: "Modulo 2/guia-hooks.pdf",
      extension: "pdf",
      fileSizeBytes: 440321,
      extractedTextPreview: "Resumen de composición de hooks, side effects y patrones de extracción.",
      thumbnailPath: null,
    },
    {
      id: 711,
      lessonId: 110,
      courseId: 1,
      assetKind: "subtitle",
      title: "Subtítulos ES",
      absolutePath: "D:/Cursos/React/Modulo 2/02-async-await.es.vtt",
      relativePath: "Modulo 2/02-async-await.es.vtt",
      extension: "vtt",
      fileSizeBytes: 8243,
      extractedTextPreview: "Async await no bloquea el hilo principal.",
      thumbnailPath: null,
    },
  ],
  lessonSummary:
    "Modulo 2: una introduccion clara al uso de async/await, al ritmo de trabajo de React y a la forma de evitar bloqueos o efectos innecesarios.",
  lessonTranscriptPreview:
    "Async await no bloquea el hilo principal. La clase muestra cuando conviene esperar una respuesta, como cancelar trabajo pendiente y como mantener una interfaz fluida mientras llegan los datos.",
  lessonHighlights: [
    "Que cambia cuando una accion depende de una respuesta externa.",
    "Como evitar estados inconsistentes mientras la pantalla sigue siendo rapida.",
    "Ejemplos sencillos para aplicar la idea en componentes reales.",
  ],
  previousLessonId: null,
  nextLessonId: 111,
  courseTitle: "React Profundo para Apps Reales",
  sectionTitle: "Módulo 2 · Estado y asincronía",
  completionThresholdPercent: 92,
};

export const mockSearchResults: SearchResult[] = [
  {
    entityType: "lesson",
    entityId: 110,
    title: "02. Async Await sin fricción",
    snippet: "Explicación de async/await, cancelación de efectos y manejo de errores en componentes React.",
    score: 0.93,
    lexicalScore: 0.84,
    semanticScore: 0.97,
    courseId: 1,
    lessonId: 110,
  },
  {
    entityType: "asset",
    entityId: 710,
    title: "Guía PDF de Hooks Avanzados",
    snippet: "Documento con patrones de hooks, composición y estado derivado.",
    score: 0.81,
    lexicalScore: 0.79,
    semanticScore: 0.82,
    courseId: 1,
    lessonId: null,
  },
];
